### ISSUE TITLE
Configure Settings broken

### ISSUE THREAD

**Issue by crazyclausewitz** [vttred/ose#228]
### What happened?

Clicking on the 'Configure Settings' button on the 'Game Settings' tab does nothing.

### What is the expected behaviour?

Show the settings for the game settings for the OSE module.

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.6.3

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
I can't reproduce this. To make sure, you don't have an error message in the developer console upon clicking the button? (press F12 in most browsers)

**Comment by crazyclausewitz** [comment]
Yes, there is indeed an error message:

foundry.js:4950 Foundry VTT | Rendering SettingsConfig
foundry.js:711 Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
[No packages detected]
    at SchemaField._validateType (commons.js:3630:15)
    at SchemaField.validate (commons.js:3357:37)
    at Setting.validate (commons.js:4994:35)
    at new DataModel (commons.js:4771:26)
    at new Document (commons.js:5310:3)
    at new BaseSetting (commons.js:9319:3)
    at new ClientDocumentMixin (foundry.js:12942:5)
    at new Setting (foundry.js:21144:1)
    at ClientSettings.get (foundry.js:2718:19)
    at SettingsConfig._prepareCategoryData (foundry.js:70821:31)
    at SettingsConfig.getData (foundry.js:58949:23)
    at SettingsConfig._render (foundry.js:4959:29)
    at SettingsConfig._render (foundry.js:5684:17)
    at SettingsConfig._render (foundry.js:59018:18)
onError @ foundry.js:711
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:4920
Promise.catch (async)
render @ foundry.js:4918
_onSettingsButton @ foundry.js:75548
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by crazyclausewitz** [comment]
Ok, debugged it myself: Seems to be a problem with the libWrapper module.
I think you can close this.

**Comment by anthonyronda** [comment]
Thanks for figuring it out and letting me know
