### ISSUE TITLE
[V11.311] Error: You are accessing CONFIG.Actor.systemDataModels which is deprecated

### ISSUE THREAD

**Issue by PXR5** [vttred/ose#472]
### What happened?

Two deprecation warnings in the log when loading OSE worlds, using Brave browser...

commons.js:2065 Error: You are accessing CONFIG.Actor.systemDataModels which is deprecated. Please use CONFIG.Actor.dataModels instead.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at Object.logCompatibilityWarning (commons.js:2054:19)
    at Object.set (foundry.js:91634:21)
    at Object.fn (ose.js:78:16)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.initialize (foundry.js:8576:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)

commons.js:2065 Error: You are accessing CONFIG.Item.systemDataModels which is deprecated. Please use CONFIG.Item.dataModels instead.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at Object.logCompatibilityWarning (commons.js:2054:19)
    at Object.set (foundry.js:91634:21)
    at Object.fn (ose.js:82:15)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.initialize (foundry.js:8576:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)

### Additional Support Details

Foundry Virtual Tabletop: Version 11 Stable, 11.311
Game System: ose, 1.9.3
Active Modules: 25
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
GPU: ANGLE (Apple, Apple M1, OpenGL 4.1)
Max Texture Size: 16384

Scene: 6000 x 4600 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 8

Actors: 72 | Items: 63 | Journal Entries: 8 | Rollable Tables: 5 |
Playlists: 0 | Compendium Packs: 42 | Chat Messages: 126

### Foundry VTT Core Version

V11

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
Soon we're dropping V10 support, which will allow us to remove deprecated API calls
