### ISSUE TITLE
Hardcored ose-dev in template path breaks group selector in combat tracker

### ISSUE THREAD

**Issue by arcos** [vttred/ose#535]
### What happened?

1. Add a bunch of tokens to combat tracker
2. click on the group "Set Combatant Groups" flag icon
3. On an non-dev build you will get an error in the console about not being able to find the template and the group selector modal doesn't open.

### What is the expected behaviour?

The template path is set to the production build path and the group selector opens.

### Relevant Errors and Warnings

```shell
foundry.js:7839 Uncaught (in promise) Error: ENOENT: no such file or directory, open '<path>\systems\ose-dev\dist\templates\apps\combat-set-groups.hbs'
[No packages detected]
    at a.<anonymous> (foundry.js:7839:39)
    at a.value (socket.js:580:13)
    at a.value (socket.js:499:22)
    at U.emit (index.mjs:136:20)
    at manager.js:204:18
(anonymous)	@	foundry.js:7839
value	@	socket.js:580
value	@	socket.js:499
U.emit	@	index.mjs:136
(anonymous)	@	manager.js:204
```

This can be corrected on line 44 of `src\module\combat\combat-set-groups.ts`
```


### Additional Support Details

_No response_

### Foundry VTT Core Version

None

### Old-School Essentials Core Version

_No response_

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rughalt** [comment]
This was fixed by #537
